#define BASELINE_NAME "xpb_bootloader_v2_0a_0"
#define BASELINE_NAME_ALT 'xpb_bootloader_v2_0a_0'
#define BASELINE_VERSION 2
#define BASELINE_VERSION_STRING "2"
#define BASELINE_VERSION_STRING_ALT '2'

#define BASELINE_MAJOR_VERSION 2
#define BASELINE_MAJOR_VERSION_STRING "2"
#define BASELINE_MAJOR_VERSION_STRING_ALT '2'
#define BASELINE_MINOR_VERSION 0
#define BASELINE_MINOR_VERSION_STRING "0"
#define BASELINE_MINOR_VERSION_STRING_ALT '0'
#define BASELINE_TYPE_STRING "a"
#define BASELINE_TYPE_STRING_ALT 'a'

#define BASELINE_BUILD 0
#define BASELINE_BUILD_STRING "0"
#define BASELINE_BUILD_STRING_ALT '0'
#define BASELINE_PROJECT "xpb_bootloader"
#define BASELINE_PROJECT_ALT 'xpb_bootloader'
#define BASELINE_DATE "Sunday, 10 9, 2022 12:00:00"
#define BASELINE_DATE_ALT 'Sunday, 10 9, 2022 12:00:00'

#define GIT_COMMIT_SHA "coffee"
#define GIT_COMMIT_SHA_ALT 'coffee'

